version: '3.8'
services:
  warehouse:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
    volumes:
      - ./warehouse:/var/lib/postgresql/data
    ports:
      - 5432:5432